[destination.snowflake.credentials]
database = "movies" 
username = "extract_loader" 
password = "meja1234" # please set me up!
host = "LGPOTYU-LU26023" # please set me up!  
warehouse = "COMPUTE_WH" 
role = "movies_dlt_role"